### ISSUE TITLE
Bug: Action run install before cache setup

### ISSUE THREAD

**Issue by patricklx** [NullVoxPopuli/action-setup-pnpm#13]
This action runs pnpm install before loading the cache.
Is this correct, shouldn't it load the cache first?
At least in ci i see it runs the install, always with 0 reuse and many download .
It just looks nice afterwards, because after this setup, people tend to run pnpm i, which then does nothing because it was already run

https://github.com/NullVoxPopuli/action-setup-pnpm/blob/9b4fb19d5397a9daacf3c9529d729c5284c4ec22/action.yml#L113C1-L113C1

**Comment by NullVoxPopuli** [comment]
Thanks for reporting!

Could be an oversight
I think a previous iteration of this did split up the install to be after cache setup.
Here: https://github.com/NullVoxPopuli/action-setup-pnpm/blob/v1.1.0/action.yml#L35

So maybe that needs to come back

**Comment by NullVoxPopuli** [comment]
Here is the PR that probably needs a revert with a tweak: https://github.com/NullVoxPopuli/action-setup-pnpm/pull/12/files

We want the new simpler way of handling args, but with post-cache install

**Comment by patricklx** [comment]
maybe you can just switch `actions/setup-node@v3` <-> `pnpm/action-setup@v2` ?

**Comment by NullVoxPopuli** [comment]
Does that one respect volta node?
Also, seems unrelated to cache?

**Comment by patricklx** [comment]
i just mean the ordering

**Comment by NullVoxPopuli** [comment]
This is the recommended way to use cache: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

Should probably align with that

**Comment by patricklx** [comment]
okay. then the only way is to run pnpm install manually...
also, that seems to be the recommended way :) run_install: false and pnpm install at end

**Comment by NullVoxPopuli** [comment]
Yup, i'll happily accept a pr here, and i can port it to wyvox
